### ISSUE TITLE
Using OpenAI API causes UI1 to error, and not load the API.

### ISSUE THREAD

**Issue by TheZennou** [henk717/KoboldAI-Client#267]
It would seem that loading an OpenAI API while using UI1 on United causes a crash, it could be the same for the main branch, don't really know. I've been informed this is undertested, so you might see a few more issues regarding OpenAI creep up. Hopefully we can improve Kobold's support for this, even if it's not frequently used.

Here is the error:
```Exception in thread Thread-43:
Traceback (most recent call last):
  File "B:\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "B:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "B:\python\lib\site-packages\socketio\server.py", line 731, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "B:\python\lib\site-packages\socketio\server.py", line 756, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 828, in _handle_event
    ret = handler(*args)
  File "aiserver.py", line 591, in g
    return f(*a, **k)
  File "aiserver.py", line 4555, in get_message
    load_model(use_gpu=msg['use_gpu'], gpu_layers=msg['gpu_layers'], disk_layers=msg['disk_layers'], online_model=msg['online_model'])
  File "aiserver.py", line 2874, in load_model
    "CLUSTER": koboldai_vars.cluster_requested_models[0],
IndexError: list index out of range
```

Steps to reproduce: Simply try to load OpenAI API as the model while using UI1.

**Comment by ebolam** [comment]
I see the issue. I've got a fix queued up in my code base, should make it in to united in a few days. 

If you want to test, you can change line 2874 from:
"CLUSTER": koboldai_vars.cluster_requested_models[0],
to:
"CLUSTER": koboldai_vars.cluster_requested_models[0] if len(koboldai_vars.cluster_requested_models) > 0 else "gpt2",

Alas, as you say OpenAI/GooseAI, etc is undertested, especially in UI2 (in case you want to give that a shot :))

**Comment by TheZennou** [comment]
You might have fixed that, but now if you try to generate you get the following error.
```
ERROR      | __main__:generate:6325 - Traceback (most recent call last):
  File "aiserver.py", line 6312, in generate
    genout, already_generated = tpool.execute(core_generate, txt, minimum, maximum, found_entries)
  File "/notebooks/runtime/envs/koboldai/lib/python3.8/site-packages/eventlet/tpool.py", line 132, in execute
    six.reraise(c, e, tb)
  File "/notebooks/runtime/envs/koboldai/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/notebooks/runtime/envs/koboldai/lib/python3.8/site-packages/eventlet/tpool.py", line 86, in tworker
    rv = meth(*args, **kwargs)
  File "aiserver.py", line 5500, in core_generate
    result = raw_generate(
  File "aiserver.py", line 5706, in raw_generate
    batch_encoded = model_functions[koboldai_vars.model](
  File "aiserver.py", line 5884, in oai_raw_generate
    req = requests.post(
  File "/notebooks/runtime/envs/koboldai/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/notebooks/runtime/envs/koboldai/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/notebooks/runtime/envs/koboldai/lib/python3.8/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/notebooks/runtime/envs/koboldai/lib/python3.8/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/notebooks/runtime/envs/koboldai/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/notebooks/runtime/envs/koboldai/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
```
