### ISSUE TITLE
Latest play.sh returns Flask Errors

### ISSUE THREAD

**Issue by PrivateGER** [henk717/KoboldAI-Client#340]
Launching KoboldAI with the play.sh script on Linux installs the environment without errors, however every request to the server fails with an Error 500 and returns the following Flask stacktrace.
This is an Ubuntu machine.

```
AttributeError: 'Flask' object has no attribute 'session_cookie_name'
[2023-04-29 02:31:11,053] ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/home/privateger/KoboldAI/runtime/envs/koboldai/lib/python3.8/site-packages/flask/app.py", line 2189, in wsgi_app
    ctx.push()
  File "/home/privateger/KoboldAI/runtime/envs/koboldai/lib/python3.8/site-packages/flask/ctx.py", line 377, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/home/privateger/KoboldAI/runtime/envs/koboldai/lib/python3.8/site-packages/flask_session/sessions.py", line 329, in open_session
    sid = request.cookies.get(app.session_cookie_name)
AttributeError: 'Flask' object has no attribute 'session_cookie_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/privateger/KoboldAI/runtime/envs/koboldai/lib/python3.8/site-packages/flask/app.py", line 1508, in finalize_request
    response = self.process_response(response)
  File "/home/privateger/KoboldAI/runtime/envs/koboldai/lib/python3.8/site-packages/flask/app.py", line 2005, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/privateger/KoboldAI/runtime/envs/koboldai/lib/python3.8/site-packages/flask_session/sessions.py", line 353, in save_session
    if session.modified:
AttributeError: 'NoneType' object has no attribute 'modified'
```

**Comment by henk717** [comment]
Flask did a breaking update a few hours ago, just fixed it in the dependency files so if you git pull and run install_requirements.sh again it should fix it for you

**Comment by PrivateGER** [comment]
Thanks, that does fix it :)
