### ISSUE TITLE
No module named 'numpy'

### ISSUE THREAD

**Issue by ghost** [henk717/KoboldAI-Client#513]
I get this error when try to start to start KoboldAI. I already have numpy installed, so I don't know why I get this error.

```
/home/admin/KoboldAI-Snapshot-23-01-24/runtime/envs/koboldai/lib/python3.8/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /opt/conda/conda-bld/pytorch_1702400431970/work/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "aiserver.py", line 15, in <module>
    from modeling.inference_model import GenerationMode
  File "/home/admin/KoboldAI-Snapshot-23-01-24/modeling/inference_model.py", line 11, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by henk717** [comment]
I recommend git cloning this repo directly if you do not use Windows, the releases are only meant for windows users.
Then after cloning try running trough play.sh. If it still doesn't work try catching the error during the installation of the runtime.

**Comment by ghost** [comment]
Thank you, I cloned the repo and it works now.
